name: top level name

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:


env:
  SLAVA: ${{ secrets.SLAVA }}

jobs:
  words-after-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: run python with secret
        env:
          SLAVA: ${{ secrets.SLAVA }}
        run: |-
            python3 test_slava.py
